---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-added-large-files
            args: [--maxkb=5000]
          - id: check-ast
          - id: check-json
          - id: check-merge-conflict
          - id: check-toml
          - id: check-yaml
          - id: debug-statements
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: pretty-format-json
            args: [--autofix]
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: trailing-whitespace

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.11.8
      hooks:
          - id: ruff
            args: [--fix]

    - repo: https://github.com/psf/black
      rev: 25.1.0
      hooks:
          - id: black
    - repo: https://github.com/astral-sh/uv-pre-commit
      rev: 0.7.3
      hooks:
          - id: uv-lock
