---
name: pre-commit
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3
            - name: Install the latest version of uv
              uses: astral-sh/setup-uv@v5
              with:
                  enable-cache: true
                  cache-dependency-glob: .pre-commit-config.yaml
            - run: uv run --no-sync --with pre-commit-uv pre-commit run --show-diff-on-failure --color=always --all-files
              shell: bash
on:
    pull_request:
        branches:
            - main
            - dev
    push:
        branches:
            - main
            - dev
permissions: read-all
